[package]
name = "shell_rust"
version = "0.1.0"
authors = ["damoswl <damoswl@foxmail.com>","SixiangZhang <sz94706@uga.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
